/**
 * login
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2.14
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface SSOLoginRequest {
    /**
     * OAuth provider ID
     */
    provider: string;
    
    /**
     * OAuth authorization code
     */
    code: string;
    
    /**
     * OAuth state parameter
     */
    state?: string;
    
    /**
     * OAuth redirect URI
     */
    redirect_uri?: string;
}